name: CI

on: push

jobs:
  v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: parisk
          password: ${{ secrets.GHCR_IMAGES_TOKEN }}
      - uses: docker/bake-action@v4
        env:
          TAG: ${{ github.sha }}
        with:
          push: true
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      